import {
  LayoutDashboard,
  Lightbulb,
  Rocket,
  FileText,
  Pen,
  Image,
  BarChart2,
  GitBranch,
  CalendarDays,
  Users,
  Shield,
  LineChart,
  Bot,
  CreditCard,
  Settings,
} from 'lucide-react';
import type { NavItem } from '@/types/navigation';

export const navItems: NavItem[] = [
  {
    id: 'command-center',
    label: 'Command Center',
    icon: LayoutDashboard,
    active: true,
    comingSoon: false,
    group: 'Visão geral',
  },
  {
    id: 'strategy-core',
    label: 'Strategy Core',
    icon: Lightbulb,
    active: false,
    comingSoon: true,
    group: 'Estratégia e Lançamento',
  },
  {
    id: 'launch-strategy-room',
    label: 'Launch Strategy Room',
    icon: Rocket,
    active: false,
    comingSoon: true,
    group: 'Estratégia e Lançamento',
  },
  {
    id: 'conteudo-matriz',
    label: 'ConteúdoMatriz',
    icon: FileText,
    active: false,
    comingSoon: true,
    group: 'Conteúdo',
  },
  {
    id: 'copy-room',
    label: 'Copy Room',
    icon: Pen,
    active: false,
    comingSoon: true,
    group: 'Conteúdo',
  },
  {
    id: 'creative-room',
    label: 'Creative Room',
    icon: Image,
    active: false,
    comingSoon: true,
    group: 'Conteúdo',
  },
  {
    id: 'traffic-room',
    label: 'Traffic Room',
    icon: BarChart2,
    active: false,
    comingSoon: true,
    group: 'Tráfego e Funil',
  },
  {
    id: 'funnel-map',
    label: 'Funnel Map',
    icon: GitBranch,
    active: false,
    comingSoon: true,
    group: 'Tráfego e Funil',
  },
  {
    id: 'calendar-execution',
    label: 'Calendar & Execution',
    icon: CalendarDays,
    active: false,
    comingSoon: true,
    group: 'Execução',
  },
  {
    id: 'mentor-flow',
    label: 'MentorFlow',
    icon: Users,
    active: false,
    comingSoon: true,
    group: 'Execução',
  },
  {
    id: 'proof-vault',
    label: 'Proof Vault',
    icon: Shield,
    active: false,
    comingSoon: true,
    group: 'Ativos',
  },
  {
    id: 'analytics',
    label: 'Analytics & AI Diagnosis',
    icon: LineChart,
    active: false,
    comingSoon: true,
    group: 'Ativos',
  },
  {
    id: 'ai-agents',
    label: 'AI Agents',
    icon: Bot,
    active: false,
    comingSoon: true,
    group: 'Sistema',
  },
  {
    id: 'billing',
    label: 'Billing & Créditos',
    icon: CreditCard,
    active: false,
    comingSoon: true,
    group: 'Sistema',
  },
  {
    id: 'settings',
    label: 'Settings & Integrations',
    icon: Settings,
    active: false,
    comingSoon: true,
    group: 'Sistema',
  },
];

export const navGroups = [
  'Visão geral',
  'Estratégia e Lançamento',
  'Conteúdo',
  'Tráfego e Funil',
  'Execução',
  'Ativos',
  'Sistema',
] as const;
